# Generated by Django 4.2.7 on 2023-11-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_slugproduct_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slugCategory',
            new_name='slug',
        ),
    ]
