# Generated by Django 4.2.7 on 2023-12-11 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_slugcategory_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countStar', models.IntegerField(default=0, verbose_name='Количество звезд у отзыва')),
            ],
            options={
                'verbose_name': 'Количество звезд у отзыва',
                'verbose_name_plural': 'Количество звезд у отзыва',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='starReview',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.star'),
        ),
    ]
