# Generated by Django 4.2.7 on 2024-05-13 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_star_alter_review_starreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-dateReview'], 'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('objectsReview', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='star',
            managers=[
                ('objectsStar', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='emailBuyerAccount',
            field=models.CharField(default='', max_length=150, verbose_name='Ваш email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='nameReview',
            field=models.CharField(default='', max_length=50, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='starReview',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.star', verbose_name='Оценка от 1 до 5'),
        ),
        migrations.AlterField(
            model_name='review',
            name='textReview',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ваш отзыв'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nameProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items_name', to='main.product')),
                ('priceOnMoneyProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items_price', to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
