# Generated by Django 4.2.7 on 2024-05-14 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_cartitem_managers_remove_cartitem_nameproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='loginAccountChat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
